"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * ライトに影響を受けない、ソリッドな切断面をもつマテリアル
 */
exports.default = (function () {
    // language=GLSL
    return "\n#define PHONG\n\n#include <mesh_phong_uniform>\nvarying vec2 uvPosition;\n#include <mesh_position_varying>\n\nuniform vec3 cutSectionColor;\n\n#include <common>\n#include <packing>\n#include <dithering_pars_fragment>\n#include <color_pars_fragment>\n#include <uv_pars_fragment>\n#include <uv2_pars_fragment>\n#include <map_uniform_chunk>\n#include <alphamap_pars_fragment>\n#include <aomap_pars_fragment>\n#include <lightmap_pars_fragment>\n#include <emissivemap_pars_fragment>\n#include <envmap_pars_fragment>\n#include <gradientmap_pars_fragment>\n#include <fog_pars_fragment>\n#include <bsdfs>\n#include <lights_pars_begin>\n#include <lights_phong_pars_fragment>\n#include <shadowmap_pars_fragment>\n#include <bumpmap_pars_fragment>\n#include <normalmap_pars_fragment>\n#include <specularmap_pars_fragment>\n#include <logdepthbuf_pars_fragment>\n#include <clipping_planes_pars_fragment>\n\nvoid main() {\n    #include <clipping_planes_fragment>\n    #include <mesh_phong_diffuse_color>\n    #include <logdepthbuf_fragment>\n    \n    #include <map_fragment_begin_chunk>\n    #include <map_fragment_chunk>\n    #include <color_fragment>\n    #include <mesh_phong_switching_alpha_map>\n    #include <alphatest_fragment>\n    #include <specularmap_fragment>\n    #include <normal_fragment_begin>\n    #include <normal_fragment_maps>\n    #include <emissivemap_fragment>\n    // accumulation\n    #include <lights_phong_fragment>\n    #include <lights_fragment_begin>\n    #include <lights_fragment_maps>\n    #include <lights_fragment_end>\n    // modulation\n    #include <aomap_fragment>\n    vec3 outgoingLight = reflectedLight.directDiffuse + reflectedLight.indirectDiffuse + reflectedLight.directSpecular + reflectedLight.indirectSpecular + totalEmissiveRadiance;\n    #include <envmap_fragment>\n  \n    outgoingLight = gl_FrontFacing ? outgoingLight : cutSectionColor;\n    gl_FragColor = vec4( outgoingLight, diffuseColor.a );\n    \n    #include <tonemapping_fragment>\n    #include <encodings_fragment>\n    \n    vec4 fragment = vec4(gl_FragColor);\n    #include <fog_fragment>\n    gl_FragColor = gl_FrontFacing ? gl_FragColor : fragment;\n    \n    #include <premultiplied_alpha_fragment>\n    #include <dithering_fragment>\n}";
});
